language: go

go:
  - tip

install:
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/golang/lint/golint
  - go get github.com/wm/go-flowdock/flowdock

script:
  - $HOME/gopath/bin/golint ./...
  - go vet -x
  - go test -v ./...


deployment:
  release:
  branch: master
  commands:
  — go get github.com/mitchellh/gox
  — go get github.com/tcnksm/ghr
  — gox -ldflags "-X main.Version $BUILD_VERSION -X main.BuildDate $BUILD_DATE" -output "dist/ncd_{{.OS}}_{{.Arch}}"
  — ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace `git describe --tags` dist/